export const SIDE_VIEW_NAV_BAR_CLICK = 'SIDE_VIEW_NAV_BAR_CLICK';
export const LEFT_SIDE_VIEW_ICON_CLICK = "LEFT_SIDE_VIEW_ICON_CLICK";


/// Apps
export const FETCH_ALL_USER_APPS = "FETCH_ALL_USER_APPS";